server:
  port: 9999
  host: "localhost"
database:
  host: "localhost"
  port: 5432
  user: "superadmin"
  password: "superadmin"
  dbname: "go_be"
  maxOpenConns: 25
  maxIdleConns: 25
  connMaxLifetime: "5m"
  sslmode: "disable"
security:
  enableTLS: true
  allowedHosts:
    - "example.com"
    - "api.example.com"
redis:
  host: "localhost"
  port: 6379
  password: "password"
  db: 0
